name: DBNet
base: ['./config/icdar2015.yaml']
arch:
  type: Model
  backbone:
    type: resnet18
    pretrained: true
  neck:
    type: FPN
    inner_channels: 256
  head:
    type: DBHead
    out_channels: 2
    k: 50
post_processing:
  type: SegDetectorRepresenter
  args:
    thresh: 0.1
    box_thresh: 0.1
    max_candidates: 1000
    unclip_ratio: 1.3 # from paper
metric:
  type: QuadMetric
  args:
    is_output_polygon: false
loss:
  type: DBLoss
  alpha: 1
  beta: 10
  ohem_ratio: 3
optimizer:
  type: Adam
  args:
    lr: 0.001
    weight_decay: 0
    amsgrad: true
lr_scheduler:
  type: WarmupPolyLR
  args:
    warmup_epoch: 3
trainer:
  seed: 2
  epochs: 1200
  log_iter: 10
  show_images_iter: 50
  resume_checkpoint: ''
  finetune_checkpoint: ''
  output_dir: output
  tensorboard: false
dataset:
  train:
    dataset:
      args:
        data_path:
          - E:/Work_project/Coding/DBNet-pytorch-master/datasets/train.txt
        img_mode: RGB
    loader:
      batch_size: 1
      shuffle: true
      pin_memory: true
      num_workers: 0
      collate_fn: ''
  validate:
    dataset:
      args:
        data_path:
          - E:/Work_project/Coding/DBNet-pytorch-master/datasets/test.txt
        pre_processes:
          - type: IaaAugment # 使用imgaug进行变换
            args:
              - {'type':Resize,'args':{'size':[1.0,1.0]}}  # 这里需要使用小数的形式
          - type: ResizeShortSize
            args:
              short_size: 500
              resize_text_polys: true
        img_mode: RGB
    loader:
      batch_size: 1
      shuffle: true
      pin_memory: false
      num_workers: 0
      collate_fn: ICDARCollectFN
